# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aimagics',
                'doc_host': 'https://adrische.github.io',
                'git_url': 'https://github.com/adrische/aimagics',
                'lib_path': 'aimagics'},
  'syms': {'aimagics.core': {'aimagics.core.foo': ('core.html#foo', 'aimagics/core.py')}}}
