"""Docs: https://adrische.github.io/aimagics/utils.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/1_utils.ipynb.

# %% auto #0
__all__ = ['add_cell', 'add_cells', 'split_markdown', 'split_into_cells']

# %% ../nbs/1_utils.ipynb #1d196aca
from IPython import get_ipython

# %% ../nbs/1_utils.ipynb #f0aacf5c
def add_cell(content: str, single=False):
    """Add a new cell below the calling cell once overall execution of the cell finishes.
    
    Parameters
    ----------
    single : int
        If True, overwrites (updates) newly created cell when called multiple times.
    """
    if not isinstance(content, str): raise TypeError("Content should be string")
    if len(content) == 0: return
    shell = get_ipython()
    shell.payload_manager.write_payload(
        {"source":"set_next_input",
         "text":content,
         "replace": False}, # replaces the calling cell if True, I have never used this so it's not exposed
        single=single)

# %% ../nbs/1_utils.ipynb #c8a9f9ae
def add_cells(contents: list[str]):
    """Adds several cells below the calling cells once excution of the current cell finishes
    
    Parameters
    ----------
    contents : list[str]
        The contents to be placed in the new cells.
    """
    if not isinstance(contents, list): raise TypeError("Contents should be list (of strings)")
    for c in reversed(contents): # the calls are scheduled and executed in reversed order
        add_cell(c, single=False)

# %% ../nbs/1_utils.ipynb #5b3f3d4e
def split_markdown(md: str, max_level: int = 6) -> list[str]:
    """Splits a markdown formatted string at headers"""
    try: from mdsplit import split_by_heading
    except ModuleNotFoundError: raise ModuleNotFoundError("This function requires mdsplit, https://github.com/markusstraub/mdsplit. Please run `pip install mdsplit` to use.")

    lines = md.splitlines(keepends=True) # keepends=True preserves original newline characters without alteration
    
    return ["".join(chapter.text) for chapter in split_by_heading(lines, max_level=max_level)]

# %% ../nbs/1_utils.ipynb #8b08f313
def split_into_cells(s: str) -> tuple[list[str], list[str]]:
    "Take a markdown formatted text and split at triple backticks and insert references to cells"
    import re

    # matches ```...```   (optionally with a language hint on the opening line)
    pattern = re.compile(r'```(?:(?P<lang>\w+)\n)?(?P<content>.*?)(?<=\n)```', re.DOTALL)

    mdcells, codecells = [], []
    pos = 0 # start of the next “non‑code” slice
    for i, m in enumerate(pattern.finditer(s), start=1):
        md, c = s[pos:m.start()], m['content'] # text before the code block, code within the fences

        # formatting of md
        md = md + f"[See code cell {i} below]"

        # formatting of code
        c = c.strip("\n") # strip empty lines
        c = f"# Code cell {i}\n" + c # prepend comment which code cell it is
        if m['lang'] == "bash": c = "%%bash\n" + c
        if m['lang'] == "shell": c = "%%sh\n" + c

        mdcells.append(md)
        codecells.append(c)
        pos = m.end() # move past the block for the next iteration

    # trailing text after the last block (or the whole string if no block)
    mdcells.append(s[pos:])

    return mdcells, codecells
