name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run nbdev3 GitHub Pages workflow
        uses: answerdotai/workflows/quarto-ghp3@master
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}